import { StyleSheet, Platform } from 'react-native';
import { colors, spacing, typography } from '../../../theme';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: colors.white,
  },
  safeArea: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.md,
  },
  title: {
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 40,
    letterSpacing: 0,
    color: colors.black,
    marginBottom: spacing.sm,
  },
  subtitle: {
    ...typography.bodyMedium,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.32,
    color: colors.neutral[600],
    marginBottom: spacing.sm,
  },
  howItWorks: {
    backgroundColor: colors.primary[50],
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 7,
    marginBottom: spacing.md,
  },
  howItWorksText: {
    ...typography.label,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.secondary[900],
  },
  optionsContainer: {
    flexGrow: 0,
  },
  optionsContent: {
    gap: spacing.sm,
    paddingBottom: 100,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 80,
    borderRadius: 24,
    paddingLeft: 24,
    paddingRight: 24,
    overflow: 'hidden',
    backgroundColor: colors.white,
  },
  optionRowSelected: {
    borderWidth: 2,
    borderColor: colors.primary.purple,
  },
  optionRowUnselected: {
    borderWidth: 1,
    borderColor: colors.neutral[100],
  },
  rowImageWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.neutral[50],
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowImageImg: {
    width: '100%',
    height: '100%',
  },
  optionText: {
    ...typography.bodyMedium,
    fontSize: 18,
    fontWeight: '500',
    flex: 1,
    color: colors.black,
  },
  optionTextSelected: {
    color: colors.primary.purple,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    borderColor: colors.primary.purple,
    backgroundColor: colors.primary.purple,
  },
  checkboxRankText: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 14,
    color: colors.white,
  },
  actions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    paddingHorizontal: spacing.md,
    paddingBottom: Platform.OS === 'ios' ? spacing.xl * 2 : spacing.xl,
    paddingTop: spacing.md,
    backgroundColor: colors.white,
  },
  primaryButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
  },
});
