import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../../theme';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: colors.white,
  },
  safeArea: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  content: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: spacing.md,
  },
  title: {
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 40,
    letterSpacing: 0,
    color: colors.black,
    marginBottom: spacing.sm,
  },
  subtitle: {
    ...typography.bodyMedium,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.32,
    color: colors.neutral[600],
    marginBottom: spacing.md,
  },
  listContent: {
    paddingBottom: spacing.md,
    gap: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 80,
    backgroundColor: '#f7f7f7',
    borderRadius: 24,
    paddingLeft: 24,
    paddingRight: 24,
    overflow: 'hidden',
  },
  rowLabel: {
    flex: 1,
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 26,
    letterSpacing: 0.36,
    color: colors.black,
    marginLeft: 12,
  },
  rowImageWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.white,
    overflow: 'hidden',
    alignItems: 'center',
    top: 12,
    justifyContent: 'center',
  },
  rowImageImg: {
    width: '100%',
    height: '100%',
  },
  selectionBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionBoxSelected: {
    backgroundColor: colors.secondary[500],
    borderColor: colors.secondary[500],
  },
  actions: {
    width: '100%',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    backgroundColor: colors.white,
  },
  primaryButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
  },
});
