export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    socialLogin: '/auth/social-login',
    liveness: '/auth/liveness-check',
    googleLogin: '/auth/google',
    appleLogin: '/auth/apple',
  },
  user: {
    profile: '/auth/profile',
    addprofile: '/auth/profile/add',
    update: '/user/update',
    editProfile: '/auth/profile',
    self: '/auth/self',
    selfie: '/auth/selfie',
    uploadPhotos: '/auth/gallery',
    deletePhoto: '/auth/gallery/{id}',
  },
  question: {
    getQuestions: '/questions',
    answerQuestion: '/questions/answers',
  },
  preferences: {
    editPreference: '/auth/preference',
    addPreference: '/auth/preference/add',
    getPreferences: '/auth/preference',
  },
  chat: {
    getChats: '/chat/get-chat-list',
    getpPendingChats: '/chat/get-pending-chat-list',
    setRequestAction: '/chat/chat-request-action',
    getChatMessages: '/chat/get-messages',
    markSeen: '/chat/mark-seen',
    sendMessage: '/chat/send-message',
    fileUpload: '/aws-s3-files/upload',
    readMessage: '/chat/messages/read',
    deleteMessage: '/chat/messages/delete',
    deleteChat: '/chat/delete-chat',
    pinChat: '/chat/pin-chat',
    unpinChat: '/chat/unpin-chat',
    blockUser: '/block-user' ,
    reportUser: '/report-user',
    unblockUser: '/chat/unblock',
  },
};