export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    deleteAccount: '/auth/account',
    sendOtp: '/auth/send-otp',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    socialLogin: '/auth/social-login',
    /** POST multipart `file` (JPEG) — liveness selfie vs reference photos */
    livenessVerify: '/auth/liveness/verify',
    /** POST `{ livenessCheck: true }` — mark liveness step complete on profile */
    livenessCheck: '/auth/liveness-check',
    googleLogin: '/auth/google',
    appleLogin: '/auth/apple',
    fcmToken: '/auth/fcm-token',
    supportEmailChange: '/auth/support/email-change',
    /** PATCH — body `{ isAppTourDone: true }` */
    appTour: '/auth/app-tour',
  },
  user: {
    profile: '/auth/profile',
    addprofile: '/auth/profile/add',
    update: '/user/update',
    editProfile: '/auth/profile',
    seflf: '/auth/self',
    selfie: '/auth/selfie',
    uploadPhotos: '/auth/gallery',
    deletePhoto: '/auth/gallery/{id}',
  },
  question: {
    getQuestions: '/questions',
    answerQuestion: '/questions/answers',
    getrefereceImages: '/reference-images/next',
    postReferenceImages: '/reference-images/answer',
  },
  preferences: {
    editPreference: '/auth/preference',
    addPreference: '/auth/preference/add',
    getPreferences: '/auth/preference',
  },
  matches: {
    getMatches: '/user-match-profile/matches',
    getMatchesCursor: '/user-match-profile/matches/cursor',
    saveMatchesCursor: '/user-match-profile/matches/cursor',
    getMatchesCursorPage: '/user-match-profile/matches/cursor1',
    getMatchDetails: '/user-match-profile/profile-insights/{id}',
    addLike: '/user-like',
    removeLike: '/user-like/dislike',
    getLikes: '/user-like/get-like',
  },
  chat: {
    getChats: '/chat/get-chat-list',
    getpPendingChats: '/chat/get-pending-chat-list',
    setRequestAction: '/chat/chat-request-action',
    getAiSuggestions: '/chat/chat-suggestion',
    getChatMessages: '/chat/get-messages',
    postAIMessages: '/chat/aira-introduce',
    markSeen: '/chat/mark-seen',
    sendMessage: '/chat/send-message',
    fileUpload: '/aws-s3-files/upload',
    deleteMessage: '/chat/delete-message',
    deleteChat: '/chat/delete-chat',
    pinChat: '/chat/pin-chat',
    unpinChat: '/chat/unpin-chat',
    blockUser: '/block-user' ,
    reportUser: '/report-user',
    blockreportUser: '/report-block',
    /** Users you have blocked; body `{ page, limit }`. */
    getBlockedUsers: '/block-user/get-users-i-blocked',
    addChat: 'chat/add-chat-list',
  },
  chatbot: {
    getChatbotMessages: '/ai-chat-log/get-logs',
    postChatbotMessages: '/ai-chat-log/send',
  },
  notifications: {
    list: '/notifications/list',
    /** PATCH — mark single notification seen */
    markSeen: (notificationId: string) =>
      `/notifications/${encodeURIComponent(notificationId)}/seen`,
  },
  rtc: {
    agoraToken: '/agora/token',
  },
  iap: {
    appleAppAccountToken: '/iap/apple/app-account-token',
    appleSync: '/iap/apple/sync',
    googleSync: '/iap/google/sync',
    entitlements: '/iap/entitlements',
    transactions: '/iap/transactions',
  },
};