import { StyleSheet } from 'react-native';
import { colors, typography, spacing } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.light,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: 64,
    paddingBottom: 120,
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  avatarWrapper: {
    width: 100,
    height: 100,
    marginBottom: 8,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 1000,
    backgroundColor: colors.neutral[200],
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 1000,
  },
  progressRing: {
    position: 'absolute',
    top: -3,
    left: -3,
    width: 106,
    height: 106,
  },
  progressBadge: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    backgroundColor: colors.primary.purple,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 1000,
  },
  progressBadgeText: {
    ...typography.small,
    fontWeight: '500',
    color: colors.white,
    letterSpacing: 0.48,
  },
  nameBlock: {
    alignItems: 'center',
    marginBottom: 8,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  genderReadOnly: {
    ...typography.small,
    marginTop: 4,
    color: colors.neutral[600],
    letterSpacing: 0.48,
  },
  name: {
    ...typography.bodyMedium,
    fontSize: 16,
    color: colors.black,
    letterSpacing: 0.32,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  editButtonText: {
    ...typography.small,
    fontWeight: '500',
    color: colors.black,
    letterSpacing: 0.48,
  },
  // Figma 2101-28021: card border #CB7BF5, radius 32, content left 24 top 22, gap 8 then 12
  airaPlusCard: {
    borderRadius: 32,
    borderWidth: 2,
    borderColor: colors.secondary.lavender, // #CB7BF5
    overflow: 'hidden',
    height: 187,
    marginBottom: spacing.lg,
  },
  airaPlusBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  airaPlusGradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 1,
  },
  airaPlusOverlayTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  airaPlusOverlay: {
    ...StyleSheet.absoluteFillObject,
    paddingLeft: 24,
    paddingTop: 22,
    paddingRight: 24,
    paddingBottom: 32,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 8,
  },
  airaPlusLogoRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  airaPlusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.white,
    paddingLeft: 10,
    paddingRight: 2,
    paddingVertical: 2,
    borderRadius: 100,
  },
  airaPlusPlusText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.semibold,
    lineHeight: 22,
    letterSpacing: -0.32,
  },
  airaPlusPlusTextHidden: {
    opacity: 0,
  },
  airaPlusTextBlock: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    alignSelf: 'stretch',
    paddingBottom: 16,
  },
  airaPlusText: {
    ...typography.label,
    fontSize: 14,
    fontWeight: '500',
    color: colors.white,
    letterSpacing: 0.28,
    lineHeight: 20,
  },
  airaPlusButton: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  airaPlusButtonGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  airaPlusButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.white,
    letterSpacing: 0.28,
  },
  menuList: {
    gap: 8,
    marginBottom: spacing.lg,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
    paddingVertical: 8,
    paddingHorizontal: spacing.md,
    borderRadius: 160,
  },
  menuRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  menuRowLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    color: colors.black,
    letterSpacing: 0.32,
    paddingVertical: 8,
  },
  menuRowLabelDanger: {
    color: colors.semantic.error,
  },
  footer: {
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  footerLogo: {
    marginBottom: 16,
  },
  version: {
    ...typography.body,
    fontSize: 14,
    fontWeight: '400',
    color: colors.neutral[700],
    letterSpacing: 0.28,
    marginBottom: spacing.lg,
  },
  footerActions: {
    width: '100%',
    gap: 8,
  },
  logoutButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: colors.neutral[200],
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  logoutContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  logoutText: {
    ...typography.button,
    color: colors.semantic.error,
  },
  deleteAccountButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    // backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.neutral[200],
    // borderColor: 'rgba(255, 60, 60, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteAccountContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteAccountText: {
    ...typography.button,
    color: colors.black,
  },
  /** Logout confirmation sheet — Figma 3202-15485 / 3202-15486; floating card + inset — 3202-14847 */
  logoutSheetBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  /** Applied as ReusableBottomSheet `backgroundStyle`: card inset from screen edges, all corners rounded */
  logoutSheetFloatingCard: {
    marginHorizontal: spacing.sm,
    borderTopLeftRadius: spacing.xl,
    borderTopRightRadius: spacing.xl,
    borderBottomLeftRadius: spacing.xl,
    borderBottomRightRadius: spacing.xl,
  },
  logoutSheetBody: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 8,
    gap: 24,
  },
  logoutSheetHeader: {
    alignItems: 'center',
    gap: 10,
    width: '100%',
  },
  logoutSheetIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 1000,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteSheetIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 1000,
    backgroundColor: 'rgba(255, 60, 60, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255, 60, 60, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteSheetBody: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 8,
    gap: 24,
  },
  deleteSheetHeader: {
    alignItems: 'center',
    gap: 10,
    width: '100%',
    paddingHorizontal: 8,
  },
  deleteReasonInputWrap: {
    width: '100%',
    marginTop: 4,
  },
  deleteReasonList: {
    width: '100%',
    marginTop: 4,
    gap: 8,
  },
  deleteReasonRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.neutral[100],
    gap: 10,
  },
  deleteReasonRowSelected: {
    backgroundColor: colors.primary[50],
    borderColor: colors.primary[50],
  },
  deleteReasonCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteReasonCheckboxSelected: {
    borderColor: colors.primary.purple,
    backgroundColor: colors.primary.purple,
  },
  deleteReasonRowLabel: {
    flex: 1,
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[800],
    lineHeight: 20,
  },
  deleteReasonRowLabelSelected: {
    color: colors.primary.purple,
  },
  deleteReasonInput: {
    minHeight: 88,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.neutral[100],
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.black,
    ...typography.body,
    fontSize: 14,
    lineHeight: 20,
  },
  deleteSheetTitle: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.black,
    textAlign: 'center',
    lineHeight: 32,
  },
  deleteSheetMessage: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '400',
    color: colors.neutral[500],
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 6,
  },
  deleteSheetActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 8,
  },
  deleteSheetCancelButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteSheetCancelLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
    letterSpacing: 0.32,
  },
  logoutSheetTitle: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.black,
    textAlign: 'center',
    lineHeight: 32,
  },
  logoutSheetMessage: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '400',
    color: colors.neutral[400],
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 4,
  },
  logoutSheetActions: {
    width: '100%',
    gap: 8,
  },
  logoutSheetStayButton: {
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  logoutSheetStayGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  logoutSheetStayLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
    letterSpacing: 0.32,
  },
  logoutSheetConfirmButton: {
    height: 54,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutSheetConfirmLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
    letterSpacing: 0.32,
  },
  deleteSheetDeleteButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
    backgroundColor: colors.primary.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteSheetDeleteGradient: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteSheetDeleteButtonDisabled: {
    backgroundColor: colors.neutral[300],
  },
  deleteSheetDeleteLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
    letterSpacing: 0.32,
  },
});
