import { StyleSheet } from 'react-native';

import { colors, typography } from '../../theme';
import {
  MANAGE_DETAILS_PAD,
  MANAGE_DETAILS_RADIUS,
  MANAGE_FOOTER_BUTTON_HEIGHT,
  MANAGE_HERO_HEIGHT,
  MANAGE_RENEWAL_BANNER_RADIUS,
  MANAGE_SCREEN_PAD_H,
  MANAGE_SECTION_GAP,
} from './manageLayout';

export const manageStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  scrollContent: {
    paddingHorizontal: MANAGE_SCREEN_PAD_H,
    paddingTop: 16,
    gap: MANAGE_SECTION_GAP,
  },
  heroCard: {
    height: MANAGE_HERO_HEIGHT,
  },
  detailsCard: {
    backgroundColor: colors.white,
    borderRadius: MANAGE_DETAILS_RADIUS,
    borderWidth: 1,
    borderColor: colors.neutral[50],
    padding: MANAGE_DETAILS_PAD,
    gap: 16,
  },
  detailsTitle: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    fontFamily: typography.fontFamily.medium,
    color: colors.black,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.neutral[100],
  },
  detailRows: { gap: 16 },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  detailIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLabel: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[800],
  },
  detailValue: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    fontFamily: typography.fontFamily.medium,
    color: colors.black,
    textAlign: 'right',
  },
  detailValueColumn: { alignItems: 'flex-end' },
  detailSubValue: {
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontFamily: typography.fontFamily.medium,
    color: colors.primary.purple,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusBadgeActive: { backgroundColor: '#EEF6EE' },
  statusBadgeCancelled: { backgroundColor: '#FFF7E6' },
  statusBadgeEnded: { backgroundColor: colors.neutral[50] },
  statusBadgeText: {
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontFamily: typography.fontFamily.medium,
  },
  statusTextActive: { color: '#009900' },
  statusTextCancelled: { color: '#B36B00' },
  statusTextEnded: { color: colors.neutral[600] },
  renewalBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: colors.primary[50],
    borderRadius: MANAGE_RENEWAL_BANNER_RADIUS,
    padding: 8,
  },
  renewalIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  renewalText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[800],
  },
  renewalTextStrong: {
    fontFamily: typography.fontFamily.medium,
    color: colors.black,
  },
  footer: {
    paddingHorizontal: MANAGE_SCREEN_PAD_H,
    paddingTop: 12,
    gap: 12,
    backgroundColor: colors.white,
  },
  cancelButton: {
    height: MANAGE_FOOTER_BUTTON_HEIGHT,
    borderRadius: 100,
    backgroundColor: colors.neutral[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.32,
    fontFamily: typography.fontFamily.medium,
    color: colors.black,
  },
  helpRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  helpMuted: {
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[500],
  },
  helpLink: {
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontFamily: typography.fontFamily.medium,
    color: colors.black,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: typography.fontFamily.medium,
    color: colors.neutral[500],
  },
});
