import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../theme';
import {
  SUBSCRIPTION_BOTTOM_PANEL_GAP,
  SUBSCRIPTION_BOTTOM_PANEL_HEIGHT,
  SUBSCRIPTION_BOTTOM_PANEL_PAD_BOTTOM,
  SUBSCRIPTION_BOTTOM_PANEL_PAD_H,
  SUBSCRIPTION_BOTTOM_PANEL_PAD_TOP,
  SUBSCRIPTION_CLOSE_RIGHT,
  SUBSCRIPTION_CLOSE_SIZE,
  SUBSCRIPTION_CTA_HEIGHT,
  SUBSCRIPTION_FEATURE_ICON_BORDER,
  SUBSCRIPTION_FEATURE_ICON_RADIUS,
  SUBSCRIPTION_FEATURE_ICON_SIZE,
  SUBSCRIPTION_FEATURE_ROW_GAP,
  SUBSCRIPTION_FEATURE_TEXT_GAP,
  SUBSCRIPTION_FEATURES_GAP,
  SUBSCRIPTION_FEATURES_PADDING_H,
  SUBSCRIPTION_FEATURES_TOP_GAP,
  SUBSCRIPTION_GRADIENT_END,
  SUBSCRIPTION_GRADIENT_START,
  SUBSCRIPTION_HEADER_GAP,
  SUBSCRIPTION_HEADER_LEFT,
  SUBSCRIPTION_HEADER_TOP,
  SUBSCRIPTION_LEGAL_MAX_WIDTH,
  SUBSCRIPTION_LOGO_BLOCK_GAP,
  SUBSCRIPTION_LOGO_ROW_GAP,
  SUBSCRIPTION_PLUS_INNER_GAP,
  SUBSCRIPTION_PLUS_PAD_LEFT,
  SUBSCRIPTION_PLUS_PAD_RIGHT,
  SUBSCRIPTION_PLUS_PAD_V,
  SUBSCRIPTION_PRICE_PILL_GAP,
  SUBSCRIPTION_PRICE_PILL_HEIGHT,
  SUBSCRIPTION_PRICE_PILL_OVERLAP,
  SUBSCRIPTION_PRICE_PILL_PAD_H,
  SUBSCRIPTION_PRICE_PILL_PAD_V,
  SUBSCRIPTION_PRICE_PILL_WIDTH,
  SUBSCRIPTION_SUBTITLE_MAX_WIDTH,
} from './layout';

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: colors.primary[800],
  },
  safeArea: {
    flex: 1,
  },
  canvas: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  main: {
    flex: 1,
  },

  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  loadingText: {
    marginTop: spacing.md,
    fontSize: 14,
    fontFamily: typography.fontFamily.medium,
    color: 'rgba(255,255,255,0.7)',
    lineHeight: 20,
  },
  premiumEmoji: {
    fontSize: 56,
    marginBottom: spacing.md,
  },
  premiumTitle: {
    fontSize: 26,
    fontFamily: typography.fontFamily.semibold,
    color: colors.white,
    textAlign: 'center',
  },
  premiumSubtitle: {
    fontSize: 14,
    fontFamily: typography.fontFamily.medium,
    color: colors.neutral[200],
    marginTop: spacing.sm,
    textAlign: 'center',
    lineHeight: 20,
  },

  header: {
    paddingHorizontal: SUBSCRIPTION_HEADER_LEFT,
    paddingTop: SUBSCRIPTION_HEADER_TOP,
    gap: SUBSCRIPTION_HEADER_GAP,
  },
  upgradeToText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 22,
  },
  closeButton: {
    position: 'absolute',
    top: SUBSCRIPTION_HEADER_TOP,
    right: SUBSCRIPTION_CLOSE_RIGHT,
    zIndex: 10,
    width: SUBSCRIPTION_CLOSE_SIZE,
    height: SUBSCRIPTION_CLOSE_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoBlock: {
    gap: SUBSCRIPTION_LOGO_BLOCK_GAP,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: SUBSCRIPTION_LOGO_ROW_GAP,
  },
  plusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SUBSCRIPTION_PLUS_INNER_GAP,
    backgroundColor: colors.white,
    paddingLeft: SUBSCRIPTION_PLUS_PAD_LEFT,
    paddingRight: SUBSCRIPTION_PLUS_PAD_RIGHT,
    paddingVertical: SUBSCRIPTION_PLUS_PAD_V,
    borderRadius: 100,
  },
  plusText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.semibold,
    lineHeight: 22,
    letterSpacing: -0.32,
  },
  plusTextHidden: {
    opacity: 0,
  },
  subtitleText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 16,
    letterSpacing: 0.32,
    maxWidth: SUBSCRIPTION_SUBTITLE_MAX_WIDTH,
  },

  featuresList: {
    paddingHorizontal: SUBSCRIPTION_FEATURES_PADDING_H,
    marginTop: SUBSCRIPTION_FEATURES_TOP_GAP,
    gap: SUBSCRIPTION_FEATURES_GAP,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SUBSCRIPTION_FEATURE_ROW_GAP,
  },
  featureIconContainer: {
    width: SUBSCRIPTION_FEATURE_ICON_SIZE,
    height: SUBSCRIPTION_FEATURE_ICON_SIZE,
    borderWidth: SUBSCRIPTION_FEATURE_ICON_BORDER,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: SUBSCRIPTION_FEATURE_ICON_RADIUS,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  featureTextContainer: {
    flex: 1,
    gap: SUBSCRIPTION_FEATURE_TEXT_GAP,
  },
  featureTitle: {
    fontSize: 16,
    fontFamily: typography.fontFamily.semibold,
    color: colors.white,
    lineHeight: 22,
    letterSpacing: 0.32,
  },
  featureDescription: {
    fontSize: 14,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[300],
    lineHeight: 14,
    letterSpacing: 0.28,
  },

  purchaseWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'visible',
  },
  bottomPanelWrap: {
    position: 'relative',
    overflow: 'visible',
  },
  bottomPanel: {
    backgroundColor: 'transparent',
    minHeight: SUBSCRIPTION_BOTTOM_PANEL_HEIGHT,
    paddingTop: SUBSCRIPTION_BOTTOM_PANEL_PAD_TOP,
    paddingHorizontal: SUBSCRIPTION_BOTTOM_PANEL_PAD_H,
    paddingBottom: SUBSCRIPTION_BOTTOM_PANEL_PAD_BOTTOM,
    gap: SUBSCRIPTION_BOTTOM_PANEL_GAP,
    alignItems: 'center',
  },
  pricePillOuter: {
    position: 'absolute',
    top: -SUBSCRIPTION_PRICE_PILL_OVERLAP,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 2,
    paddingHorizontal: SUBSCRIPTION_BOTTOM_PANEL_PAD_H,
  },
  pricePillShell: {
    position: 'relative',
    borderRadius: 100,
    overflow: 'hidden',
    minWidth: SUBSCRIPTION_PRICE_PILL_WIDTH,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 17.5,
    elevation: 8,
  },
  pricePillUnderlay: {
    backgroundColor: colors.primary[900],
  },
  pricePillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SUBSCRIPTION_PRICE_PILL_GAP,
    minHeight: SUBSCRIPTION_PRICE_PILL_HEIGHT,
    paddingHorizontal: SUBSCRIPTION_PRICE_PILL_PAD_H,
    paddingVertical: SUBSCRIPTION_PRICE_PILL_PAD_V,
  },
  priceAmount: {
    fontFamily: typography.fontFamily.semibold,
    color: colors.white,
    includeFontPadding: false,
    flexShrink: 0,
  },
  pricePeriod: {
    fontSize: 20,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[200],
    lineHeight: 28,
    letterSpacing: -0.2,
    includeFontPadding: false,
    flexShrink: 0,
    paddingTop: 6,
  },
  ctaButton: {
    alignSelf: 'stretch',
    width: '100%',
    height: SUBSCRIPTION_CTA_HEIGHT,
    backgroundColor: colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  ctaButtonDisabled: {
    opacity: 0.5,
  },
  ctaButtonText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: SUBSCRIPTION_GRADIENT_START,
    letterSpacing: 0.32,
    lineHeight: 22,
  },
  retryButton: {
    paddingVertical: 4,
  },
  retryText: {
    fontSize: 13,
    fontFamily: typography.fontFamily.medium,
    color: 'rgba(255,255,255,0.5)',
  },
  legalText: {
    fontSize: 12,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[200],
    textAlign: 'center',
    lineHeight: 18,
    letterSpacing: 0.48,
    maxWidth: SUBSCRIPTION_LEGAL_MAX_WIDTH,
    alignSelf: 'center',
  },

  manageHeader: {
    paddingHorizontal: SUBSCRIPTION_HEADER_LEFT,
    paddingTop: SUBSCRIPTION_HEADER_TOP,
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  manageScreenTitle: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 22,
  },
  manageLogoRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: SUBSCRIPTION_LOGO_ROW_GAP,
  },
  managePlusPill: {
    backgroundColor: colors.white,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
  },
  managePlusPillText: {
    fontSize: 14,
    fontFamily: typography.fontFamily.semibold,
    color: SUBSCRIPTION_GRADIENT_START,
    lineHeight: 18,
  },
  manageScroll: {
    flex: 1,
  },
  manageScrollContent: {
    paddingHorizontal: SUBSCRIPTION_FEATURES_PADDING_H,
    gap: spacing.lg,
  },
  manageStatusCard: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    padding: spacing.lg,
    gap: spacing.sm,
  },
  manageStatusTitle: {
    fontSize: 20,
    fontFamily: typography.fontFamily.semibold,
    color: colors.white,
    lineHeight: 28,
  },
  manageStatusSubtitle: {
    fontSize: 14,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[200],
    lineHeight: 20,
  },
  manageDetailsCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: spacing.lg,
    gap: spacing.md,
  },
  manageDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  manageDetailLabel: {
    flex: 1,
    fontSize: 14,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[300],
    lineHeight: 20,
  },
  manageDetailValue: {
    flex: 1,
    fontSize: 14,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 20,
    textAlign: 'right',
    textTransform: 'capitalize',
  },
  manageStoreButton: {
    alignSelf: 'stretch',
    height: SUBSCRIPTION_CTA_HEIGHT,
    backgroundColor: colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  manageStoreButtonText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: SUBSCRIPTION_GRADIENT_START,
    letterSpacing: 0.32,
    lineHeight: 22,
  },
  manageFootnote: {
    fontSize: 12,
    fontFamily: typography.fontFamily.regular,
    color: colors.neutral[300],
    textAlign: 'center',
    lineHeight: 18,
    letterSpacing: 0.24,
  },
  restoreLink: {
    alignSelf: 'center',
    paddingVertical: spacing.sm,
  },
  restoreLinkText: {
    fontSize: 14,
    fontFamily: typography.fontFamily.medium,
    color: 'rgba(255,255,255,0.7)',
    textDecorationLine: 'underline',
  },
});
