import {
  API_BASE_URL,
  NODE_ENV,
  API_KEY,
  GOOGLE_CLIENT_ID,
  IOS_CLIENT_ID,
  SENTRY_DSN,
  SENTRY_ENVIRONMENT,
  SENTRY_TRACES_SAMPLE_RATE,
  SENTRY_PROFILES_SAMPLE_RATE,
} from '@env';

export const env = {
  API_BASE_URL,
  NODE_ENV,
  API_KEY,
  GOOGLE_CLIENT_ID,
  IOS_CLIENT_ID,

  // Sentry (optional)
  SENTRY_DSN,
  SENTRY_ENVIRONMENT,
  SENTRY_TRACES_SAMPLE_RATE,
  SENTRY_PROFILES_SAMPLE_RATE,
};
