import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, typography } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const H_PADDING = 16;
const INPUT_PILL_BG = '#f3f3f3';
const INPUT_RADIUS = 22;
export const INPUT_BAR_HEIGHT = 56;
/** Min/max for composer TextInput: grows with text, then scrolls inside at max. */
export const CHAT_INPUT_MIN_HEIGHT = 36;
export const CHAT_INPUT_MAX_HEIGHT = 120;
const INPUT_MAX_HEIGHT = CHAT_INPUT_MAX_HEIGHT;
/** Figma 3339-7411 / Match AI composer: 48px circular actions + 12px row inset */
const MESSAGE_COMPOSER_ACTION_SIZE = 52;
const MESSAGE_COMPOSER_ROW_PADDING_H = 12;
const ATTACH_BUTTON_SIZE = MESSAGE_COMPOSER_ACTION_SIZE;
const IMAGE_BUBBLE_SIZE = 200;
const SEND_BUTTON_SIZE = MESSAGE_COMPOSER_ACTION_SIZE;
export const BUBBLE_MAX_WIDTH = SCREEN_WIDTH * 0.75;
// Figma 1690-7152: generating bar and cancel (height must fit icon + text + padding)
const GENERATING_BAR_HEIGHT = 44;
const GENERATING_CANCEL_SIZE = 40;
const GENERATING_BAR_GAP = 8;
const GENERATING_PILL_BORDER_RADIUS = 20;
const GENERATING_PILL_PADDING_V = 10;
const GENERATING_PILL_PADDING_H = 14;
const GENERATING_PILL_GAP = 8;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.neutral[200],
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.neutral[200],
    marginRight: 12,
  },
  headerNameWrap: {
    flex: 1,
    justifyContent: 'center',
  },
  headerName: {
    ...typography.bodyMedium,
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
  },
  headerOnline: {
    ...typography.small,
    color: colors.primary.purple,
    marginTop: 2,
  },
  headerAskAiraButton: {
    width: 32,
    height: 32,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
    // ...Platform.select({
    //   ios: {
    //     shadowColor: '#000',
    //     shadowOffset: { width: 0, height: 4 },
    //     shadowOpacity: 0.05,
    //     shadowRadius: 16,
    //   },
    //   android: { elevation: 2 },
    // }),
  },
  /** Figma 3597-8637 — video / voice call taps (24px icon in 40pt target). */
  headerCallButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  moreButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  incomingCallBannerWrap: {
    paddingHorizontal: 16,
    paddingTop: 8,
    width: '100%',
  },
  incomingCallBanner: {
    flexDirection: 'column',
    padding: 12,
    borderRadius: 24,
    backgroundColor: colors.neutral[100],
    gap: 10,
  },
  incomingCallBannerTitle: {
    ...typography.bodyMedium,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    fontWeight: '500',
    color: colors.neutral[900],
  },
  incomingCallBannerSubtitle: {
    ...typography.small,
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[500],
  },
  incomingCallBannerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  incomingCallBannerAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.neutral[200],
    overflow: 'hidden',
    position: 'relative',
  },
  incomingCallBannerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  incomingCallBannerAvatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.white,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingCallBannerAvatarBadgeIcon: {
    width: 10,
    height: 10,
    resizeMode: 'contain',
  },
  incomingCallBannerButtonsRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 6,
  },
  incomingCallBannerButtonPill: {
    flex: 1,
    borderRadius: 100,
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingCallBannerButtonPillInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  incomingCallBannerDeclineButton: {
    backgroundColor: '#e50000',
  },
  incomingCallBannerAcceptButton: {
    backgroundColor: '#090',
  },
  incomingCallBannerPillIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  incomingCallBannerPillText: {
    ...typography.bodyMedium,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    fontWeight: '500',
    color: colors.white,
    textAlign: 'center',
  },
  incomingVoiceBackdrop: {
    flex: 1,
    backgroundColor: colors.neutral[900],
  },
  incomingVoiceCenterWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingVoiceTitle: {
    ...typography.bodyMedium,
    marginTop: 16,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.32,
    color: colors.white,
    textAlign: 'center',
  },
  incomingVoiceAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: colors.neutral[700],
  },
  incomingVoiceActionsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 40,
  },
  incomingVoiceActionGroupSmall: {
    width: 56,
    alignItems: 'center',
    gap: 8,
  },
  incomingVoiceActionGroupCenter: {
    width: 109,
    alignItems: 'center',
    gap: 8,
  },
  incomingVoiceSwipeIndicator: {
    height: 76,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  incomingVoiceSwipeChevron: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 12,
    color: colors.neutral[500],
    marginBottom: -2,
  },
  incomingVoiceActionCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  incomingVoiceDeclineBtn: {
    backgroundColor: '#E50000',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  incomingVoiceAcceptBtn: {
    backgroundColor: '#009900',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  incomingVoiceMessageBtn: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderColor: 'rgba(255,255,255,0.1)',
  },
  incomingVoiceActionLabel: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[100],
    textAlign: 'center',
  },
  incomingVideoFullBackdrop: {
    flex: 1,
    backgroundColor: '#0C0C0C',
  },
  incomingVideoFullBgImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  incomingVideoFullBgFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#1A1A1A',
  },
  incomingVideoFullOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  incomingVideoFullTopCenter: {
    marginTop: 172,
    alignItems: 'center',
    width: 153,
    alignSelf: 'center',
  },
  incomingVideoFullAvatar: {
    width: 80,
    height: 80,
    borderRadius: 75,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: colors.neutral[700],
  },
  incomingVideoFullName: {
    ...typography.bodyMedium,
    marginTop: 4,
    color: colors.white,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '500',
    letterSpacing: 0,
    textAlign: 'center',
    maxWidth: 260,
  },
  incomingVideoFullVideoTogglePill: {
    marginTop: 8,
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(0,0,0,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  incomingVideoFullVideoToggleText: {
    ...typography.small,
    fontSize: 10,
    lineHeight: 18,
    letterSpacing: 0.4,
    color: colors.white,
  },
  incomingVideoFullActionsRow: {
    marginTop: 'auto',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 40,
    paddingHorizontal: 16,
  },
  incomingVideoFullActionGroupSmall: {
    width: 56,
    alignItems: 'center',
    gap: 8,
  },
  incomingVideoFullActionGroupCenter: {
    width: 109,
    alignItems: 'center',
    gap: 12,
  },
  incomingVideoFullSwipeIndicator: {
    width: 20,
    height: 100,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 4,
  },
  incomingVideoFullSwipeChevron: {
    ...typography.small,
    fontSize: 20,
    lineHeight: 20,
    color: colors.neutral[500],
    marginBottom: -4,
  },
  incomingVideoFullActionCircle: {
    width: 56,
    height: 56,
    borderRadius: 875,
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingVideoFullDeclineBtn: {
    backgroundColor: '#E50000',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  incomingVideoFullAcceptBtn: {
    backgroundColor: '#009900',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  incomingVideoFullMessageBtn: {
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  incomingVideoFullActionLabel: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[100],
    textAlign: 'center',
  },
  audioDeviceBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  audioDeviceSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 14,
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  audioDeviceTitle: {
    ...typography.h3,
    fontSize: 18,
    color: colors.black,
    marginBottom: 12,
  },
  audioDeviceOption: {
    height: 48,
    borderRadius: 14,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginTop: 8,
    backgroundColor: colors.neutral[50],
  },
  audioDeviceOptionActive: {
    backgroundColor: colors.primary[50],
    borderWidth: 1,
    borderColor: colors.primary[200],
  },
  audioDeviceOptionLabel: {
    ...typography.bodyMedium,
    color: colors.neutral[700],
  },
  audioDeviceOptionLabelActive: {
    color: colors.primary.purple,
    fontWeight: '600',
  },
  incomingVideoBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  incomingVideoSheet: {
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 18,
  },
  incomingVideoTitle: {
    ...typography.h3,
    color: colors.black,
    textAlign: 'center',
  },
  incomingVideoSubtitle: {
    ...typography.body,
    marginTop: 4,
    color: colors.neutral[500],
    textAlign: 'center',
  },
  incomingVideoAvatar: {
    width: 98,
    height: 98,
    borderRadius: 49,
    marginTop: 18,
    backgroundColor: colors.neutral[200],
  },
  incomingVideoMetaPill: {
    marginTop: 16,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.neutral[50],
    borderWidth: 1,
    borderColor: colors.neutral[200],
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  incomingVideoMetaText: {
    ...typography.small,
    color: colors.neutral[600],
  },
  incomingVideoActions: {
    marginTop: 20,
    width: '100%',
    flexDirection: 'row',
    gap: 10,
  },
  incomingVideoActionBtn: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  incomingVideoDeclineBtn: {
    backgroundColor: '#FFF4F4',
    borderWidth: 1,
    borderColor: '#FFD6D6',
  },
  incomingVideoAcceptBtn: {
    backgroundColor: colors.primary.purple,
  },
  incomingVideoDeclineText: {
    ...typography.bodyMedium,
    color: colors.semantic.error,
  },
  incomingVideoAcceptText: {
    ...typography.bodyMedium,
    color: colors.white,
  },
  incomingVideoNotificationWrap: {
    width: '100%',
    marginBottom: 10,
  },
  incomingVideoNotificationCard: {
    width: '100%',
    borderRadius: 24,
    backgroundColor: colors.neutral[100],
    padding: 12,
    gap: 10,
  },
  incomingVideoNotificationTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  incomingVideoNotificationAvatarWrap: {
    width: 48,
    height: 48,
  },
  incomingVideoNotificationAvatar: {
    width: 48,
    height: 48,
    borderRadius: 48,
    backgroundColor: colors.neutral[300],
  },
  incomingVideoNotificationAvatarBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  incomingVideoNotificationTextWrap: {
    flex: 1,
  },
  incomingVideoNotificationName: {
    ...typography.bodyMedium,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    color: colors.black,
  },
  incomingVideoNotificationSubtitle: {
    ...typography.small,
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[600],
  },
  incomingVideoNotificationActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 6,
  },
  incomingVideoNotificationBtn: {
    flex: 1,
    height: 36,
    borderRadius: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  incomingVideoNotificationDeclineBtn: {
    backgroundColor: colors.semantic.error,
  },
  incomingVideoNotificationAcceptBtn: {
    backgroundColor: '#009900',
  },
  incomingVideoNotificationBtnText: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.white,
  },
  videoCallBackdrop: {
    flex: 1,
    backgroundColor: '#080808',
  },
  videoCallBgImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  videoCallBgFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#1A1A1A',
  },
  videoCallTopGradient: {
    ...StyleSheet.absoluteFillObject,
    height: 200,
    top: 0,
    bottom: undefined,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  /** Figma: top fade black 80% → 40% @ mid → transparent over ~200pt */
  videoCallTopGradientLinear: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 200,
    zIndex: 8,
  },
  videoCallContentRoot: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#080808',
  },
  /** Remote / placeholder video — edge-to-edge under status bar (no SafeArea top padding). */
  videoCallMediaLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#080808',
    zIndex: 0,
  },
  videoCallForeground: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
    pointerEvents: 'box-none',
  },
  videoCallTopBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    paddingHorizontal: 16,
    paddingTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 40,
    backgroundColor: 'transparent',
    ...(Platform.OS === 'android' ? { elevation: 40 } : {}),
  },
  videoCallTopBackButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  videoCallTopNameRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 4,
    minWidth: 0,
  },
  videoCallTopNameWrap: {
    flexShrink: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  videoCallTopName: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
    textAlign: 'center',
  },
  videoCallTopHeaderSpacer: {
    minWidth: 48,
    alignItems: 'flex-end',
    justifyContent: 'center',
    minHeight: 48,
  },
  videoCallTopMicOffPill: {
    width: 28,
    height: 28,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallTopMicOffPillSelf: {
    width: 28,
    height: 28,
    borderRadius: 100,
    backgroundColor: 'rgba(229,0,0,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(229,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallTopTimerPill: {
    height: 32,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(0,0,0,0.1)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  videoCallTopTimerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E50000',
  },
  videoCallTopTimerText: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[100],
  },
  videoCallTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  videoCallTopPill: {
    height: 30,
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  videoCallTopPillText: {
    ...typography.small,
    color: colors.white,
    fontWeight: '600',
  },
  videoCallTimer: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 14,
  },
  videoCallTopActionPill: {
    height: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallTopActionText: {
    ...typography.small,
    color: colors.white,
    fontWeight: '600',
  },
  videoCallMainSurface: {
    flex: 1,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoCallRemoteSurface: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  videoCallCenterInfo: {
    alignItems: 'center',
    marginBottom: 82,
  },
  videoCallPartnerMicOffState: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 28,
    marginBottom: 54,
  },
  videoCallPartnerFullyOffState: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 28,
    marginBottom: 36,
  },
  videoCallPartnerFullyOffIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  videoCallPartnerFullyOffIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallPartnerFullyOffTitle: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '600',
    textAlign: 'center',
  },
  videoCallPartnerFullyOffSubtitle: {
    ...typography.body,
    marginTop: 8,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    maxWidth: '92%',
  },
  videoCallPartnerFullyOffStateCompact: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 0,
  },
  videoCallPartnerFullyOffAvatarCompact: {
    width: 64,
    height: 64,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: '#2D2D2D',
  },
  videoCallPartnerMicOffIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  videoCallPartnerMicOffTitle: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '600',
    textAlign: 'center',
  },
  videoCallPartnerMicOffSubtitle: {
    ...typography.body,
    marginTop: 8,
    color: 'rgba(255,255,255,0.72)',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    maxWidth: '92%',
  },
  videoCallVideoOffState: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 32,
    marginBottom: 10,
  },
  videoCallVideoOffAvatarWrap: {
    width: 128,
    height: 128,
    borderRadius: 64,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    marginBottom: 20,
  },
  videoCallVideoOffAvatar: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2E2E2E',
  },
  videoCallVideoOffName: {
    ...typography.h2,
    fontSize: 30,
    lineHeight: 36,
    color: colors.white,
    fontWeight: '600',
    textAlign: 'center',
    maxWidth: '82%',
  },
  videoCallName: {
    ...typography.h2,
    fontSize: 34,
    color: colors.white,
    fontWeight: '600',
  },
  videoCallVideoOffTitle: {
    ...typography.bodyMedium,
    marginTop: 10,
    color: colors.white,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
  },
  videoCallVideoOffSubtitle: {
    ...typography.body,
    marginTop: 8,
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 21,
    maxWidth: '86%',
  },
  videoCallStateText: {
    ...typography.body,
    marginTop: 8,
    color: 'rgba(255,255,255,0.75)',
  },
  videoCallLocalPreview: {
    position: 'absolute',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: '#1A1A1A',
    zIndex: 35,
    ...(Platform.OS === 'android' ? { elevation: 35 } : {}),
  },
  videoCallLocalPreviewAvatar: {
    width: '100%',
    height: '100%',
    backgroundColor: '#333333',
  },
  videoCallLocalPreviewOffSurface: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallLocalPreviewOffAvatar: {
    width: 32,
    height: 32,
    borderRadius: 20,
    backgroundColor: '#2C2C2C',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  /** Figma: 20×20 flip glyph inset ~16 from PIP bottom-right (no heavy pill). */
  videoCallLocalPreviewSwitchIcon: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 36,
    minHeight: 36,
  },
  videoCallLocalPreviewMicOffIcon: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallBottomControlsWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    alignItems: 'center',
    zIndex: 40,
    ...(Platform.OS === 'android' ? { elevation: 40 } : {}),
  },
  videoCallSelfMicOffNotice: {
    marginBottom: 10,
    minHeight: 32,
    borderRadius: 16,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(0,0,0,0.56)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  videoCallSelfMicOffNoticeText: {
    ...typography.small,
    fontSize: 12,
    color: colors.white,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  videoCallAudioDevicePopoverWrap: {
    position: 'absolute',
    width: 172,
    zIndex: 45,
    ...(Platform.OS === 'android' ? { elevation: 45 } : {}),
  },
  videoCallBottomControlsCapsule: {
    borderRadius: 100,
    padding: 6,
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(0,0,0,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    zIndex: 4,
  },
  videoCallBottomAction: {
    width: 56,
    height: 56,
    borderRadius: 100,
    backgroundColor: colors.neutral[900],
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  /** Fixed slot so SVG glyphs sit on the same optical center in the 56pt circle. */
  videoCallBottomActionIconSlot: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallBottomActionSelected: {
    backgroundColor: colors.white,
  },
  videoCallBottomActionEnd: {
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: '#E50000',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  videoCallControls: {
    paddingHorizontal: 14,
    paddingBottom: 28,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  videoCallControlButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  videoCallControlButtonMuted: {
    backgroundColor: 'rgba(230, 0, 0, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  videoCallControlButtonEnd: {
    backgroundColor: colors.semantic.error,
  },
  videoCallControlLabel: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 13,
  },
  videoCallControlLabelMuted: {
    fontWeight: '700',
  },
  videoCallHiddenUiWrap: {
    paddingHorizontal: 16,
    paddingBottom: 28,
    alignItems: 'center',
  },
  videoCallHiddenUiTapArea: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 50,
    ...(Platform.OS === 'android' ? { elevation: 50 } : {}),
  },
  videoCallShowUiButton: {
    height: 40,
    borderRadius: 20,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCallShowUiText: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 13,
  },
  callStateBackdrop: {
    flex: 1,
    backgroundColor: colors.neutral[900],
  },
  callStateContent: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 24,
  },
  callStateContentRinging: {
    width: '100%',
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  callStateTopRow: {
    width: '100%',
    alignItems: 'center',
  },
  callStateModePill: {
    height: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    backgroundColor: colors.primary[50],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callStateModePillText: {
    ...typography.small,
    color: colors.primary.purple,
    fontWeight: '600',
  },
  callStateCloseText: {
    ...typography.small,
    marginTop: 14,
    color: colors.neutral[600],
  },
  callStateAvatar: {
    width: 132,
    height: 132,
    borderRadius: 66,
    marginTop: 44,
    marginBottom: 24,
    backgroundColor: colors.neutral[200],
  },
  callStateAvatarRinging: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    marginTop: 0,
    marginBottom: Platform.OS === 'ios' ? 18 : 12,
  },
  callStateAvatarPicked: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginTop: 0,
    marginBottom: 12,
  },
  callStatePickedCenterWrap: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 42,
  },
  callStatePickedCenterWrapRinging: {
    justifyContent: 'flex-start',
    paddingTop: 140,
    paddingBottom: 0,
  },
  callStatePickedAvatarWrap: {
    width: 140,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Platform.OS === 'ios' ? 14 : 0,
  },
  callStatePickedOuterRing: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  callStatePickedInnerRing: {
    position: 'absolute',
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  callStateName: {
    ...typography.h2,
    fontSize: 30,
    fontWeight: '600',
    color: colors.black,
    textAlign: 'center',
  },
  callStateRingingHeader: {
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  callStateRingingBackButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  callStateRingingHeaderName: {
    ...typography.bodyMedium,
    color: colors.white,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    maxWidth: 220,
    textAlign: 'center',
  },
  callStateRingingHeaderSpacer: {
    width: 48,
    height: 48,
  },
  callStateStatusRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.neutral[50],
  },
  callStateStatusText: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.neutral[600],
  },
  callStateAudioRouteBadge: {
    marginTop: 10,
    height: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    backgroundColor: colors.primary[50],
    borderWidth: 1,
    borderColor: colors.primary[200],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callStateAudioRouteText: {
    ...typography.small,
    fontSize: 12,
    color: colors.primary.purple,
    fontWeight: '600',
  },
  callStateAudioRouteSelectedCard: {
    marginTop: 10,
    width: '100%',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.primary[50],
    borderWidth: 1,
    borderColor: colors.primary[200],
    alignItems: 'center',
  },
  callStateAudioRouteSelectedTitle: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.primary.purple,
    fontWeight: '600',
    textAlign: 'center',
  },
  callStateAudioRouteSelectedSubtitle: {
    ...typography.small,
    marginTop: 4,
    fontSize: 12,
    color: colors.neutral[600],
    textAlign: 'center',
  },
  callStateMutedNoticeWrap: {
    marginTop: 10,
    minHeight: 34,
    borderRadius: 17,
    paddingHorizontal: 12,
    backgroundColor: '#FFF4F4',
    borderWidth: 1,
    borderColor: '#FFD6D6',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callStateMutedNoticeText: {
    ...typography.small,
    fontSize: 12,
    color: colors.semantic.error,
    fontWeight: '600',
  },
  callStateSwitchingWrap: {
    marginTop: 12,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  callStateSwitchingTitle: {
    ...typography.bodyMedium,
    fontSize: 17,
    color: colors.primary.purple,
    fontWeight: '600',
    textAlign: 'center',
  },
  callStateSwitchingSubtitle: {
    ...typography.body,
    marginTop: 6,
    color: colors.neutral[500],
    textAlign: 'center',
  },
  callStateRingingWrap: {
    marginTop: Platform.OS === 'ios' ? 10 : 0,
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  callStateRingingTitle: {
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[100],
    
  },
  callStateRingingSubtitle: {
    ...typography.body,
    marginTop: 8,
    color: colors.neutral[500],
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 22,
  },
  callStateRingingActionsRow: {
    marginTop: 'auto',
    marginBottom: 30,
    width: '100%',
    alignItems: 'center',
  },
  callStateRingingActionsCapsule: {
    borderRadius: 100,
    padding: 6,
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: '#000000',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callStateRingingActionButton: {
    width: 56,
    height: 56,
    borderRadius: 100,
    backgroundColor: colors.neutral[900],
    alignItems: 'center',
    justifyContent: 'center',
  },
  callStateRingingActionButtonSelected: {
    backgroundColor: colors.white,
  },
  callStateRingingActionButtonDisabled: {
    opacity: 0.45,
  },
  callStateRingingIconWrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  callStateRingingIconWrapEnd: {
    marginLeft: 0.5,
    marginTop: 0.5,
  },
  callStateRingingIconWrapSpeaker: {
    marginLeft: 0.5,
  },
  callStateRingingIconWrapVideo: {
    marginLeft: 0.5,
  },
  callStateRingingIconWrapMic: {
    marginTop: 0.5,
  },
  callStateRingingCancelButton: {
    width: 56,
    height: 56,
    borderRadius: 100,
    borderWidth: 0.875,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: '#E50000',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 7,
    elevation: 1,
  },
  callStateRingingActionButtonMuted: {
    backgroundColor: '#3A2020',
  },
  callStateRingingActionButtonMicMuted: {
    backgroundColor: colors.white,
  },
  callStateSwitchPopupBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  callStateAudioDevicePopover: {
    position: 'absolute',
    left: 71,
    bottom: 120,
    width: 172,
  },
  callStateAudioDevicePopoverList: {
    borderRadius: 20,
    backgroundColor: colors.white,
    padding: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    gap: 4,
  },
  callStateAudioDeviceOption: {
    height: 36,
    borderRadius: 21,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  callStateAudioDeviceOptionActive: {
    backgroundColor: colors.primary[50],
  },
  callStateAudioDeviceOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  callStateAudioDeviceOptionText: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    color: colors.neutral[600],
    
  },
  callStateAudioDeviceOptionTextActive: {
    color: colors.primary.purple,
  },
  callStateSwitchPopupSheet: {
    borderRadius: 32,
    backgroundColor: colors.white,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  callStateSwitchPopupHandle: {
    width: 30,
    height: 4,
    borderRadius: 100,
    backgroundColor: '#CCCCCC',
  },
  callStateSwitchPopupIconWrap: {
    marginTop: 24,
    width: 80,
    height: 80,
    borderRadius: 100,
    backgroundColor: '#F1ECFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  callStateSwitchPopupTitle: {
    ...typography.h3,
    marginTop: 16,
    fontSize: 24,
    lineHeight: 32,
    color: colors.black,
    textAlign: 'center',
  },
  callStateSwitchPopupSubtitle: {
    ...typography.body,
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: colors.text.muted,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  callStateSwitchPopupActions: {
    marginTop: 24,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  callStateSwitchPopupCancelButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  callStateSwitchPopupCancelText: {
    ...typography.button,
    color: colors.black,
  },
  callStateSwitchPopupSwitchButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  callStateSwitchPopupSwitchGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
  },
  callStateSwitchPopupSwitchText: {
    ...typography.button,
    color: colors.white,
  },
  callConnectedBadge: {
    marginTop: 14,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary[50],
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  callConnectedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00A651',
  },
  callConnectedBadgeText: {
    ...typography.small,
    color: colors.primary.purple,
    fontWeight: '600',
  },
  callConnectedTimer: {
    ...typography.small,
    color: colors.neutral[700],
    fontWeight: '600',
  },
  callStateMetaGrid: {
    marginTop: 18,
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  callStateMetaPill: {
    height: 32,
    borderRadius: 16,
    paddingHorizontal: 12,
    backgroundColor: colors.primary[50],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  callStateMetaLabel: {
    ...typography.small,
    color: colors.primary.purple,
    fontSize: 12,
  },
  callStateActionsRow: {
    marginTop: 'auto',
    marginBottom: 0,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  callStateActionButton: {
    minWidth: 102,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: colors.primary[100],
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  callStateActionButtonMuted: {
    backgroundColor: '#FFF4F4',
    borderColor: '#FFD6D6',
  },
  callStateActionDanger: {
    borderColor: '#FFD6D6',
    backgroundColor: '#FFF4F4',
  },
  callStateActionLabel: {
    ...typography.bodyMedium,
    fontSize: 13,
    color: colors.primary.purple,
  },
  callStateActionLabelMuted: {
    color: colors.semantic.error,
    fontWeight: '700',
  },
  callStateActionLabelDanger: {
    color: colors.semantic.error,
  },
  callStateSwitchToVideoButton: {
    marginTop: 10,
    width: '100%',
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.primary[50],
    borderWidth: 1,
    borderColor: colors.primary[200],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  callStateSwitchToVideoLabel: {
    ...typography.bodyMedium,
    color: colors.primary.purple,
    fontSize: 14,
    fontWeight: '600',
  },
  moreMenuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  moreMenu: {
    position: 'absolute',
    // `top` / `right` come from measureInWindow on the overflow button so the sheet
    // sits flush under the icon and stays out of the message list.
    minWidth: 172,
    backgroundColor: '#F2F2F2',
    borderRadius: 14,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  moreMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 8,
  },
  moreMenuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    // backgroundColor: colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  moreMenuIconWrapReport: {
    backgroundColor: 'rgba(230, 0, 0, 0.12)',
  },
  moreMenuLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  moreMenuLabelReport: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  messageContextBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  messageContextBackdropCentered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageContextBubble: {
    backgroundColor: colors.white,
    borderRadius: 16,
    minWidth: 172,
    paddingVertical: 10,
    paddingHorizontal: 4,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
  },
  messageContextItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 12,
  },
  messageContextItemDelete: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 12,
  },
  messageContextLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  messageContextLabelDelete: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.semantic.error,
  },
  deleteConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  deleteConfirmSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 12,
    paddingBottom: 34,
    paddingHorizontal: H_PADDING,
    alignItems: 'center',
    marginHorizontal: 8,
    marginBottom: 8,
  },
  deleteConfirmHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.neutral[300],
    marginBottom: 20,
  },
  deleteConfirmTitle: {
    ...typography.bodyMedium,
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
    marginBottom: 8,
    textAlign: 'center',
  },
  deleteConfirmDescription: {
    ...typography.bodyMedium,
    fontSize: 15,
    fontWeight: '400',
    color: colors.neutral[600],
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  deleteConfirmButtonDelete: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.semantic.error,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  deleteConfirmButtonCancel: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.neutral[100],
    borderWidth: 1,
    borderColor: colors.neutral[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmButtonLabelDelete: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  deleteConfirmButtonLabelCancel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  // Block confirmation popup (Figma 2636-12039)
  blockConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  blockConfirmSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 16,
    paddingBottom: 32,
    paddingHorizontal: H_PADDING,
    alignItems: 'center',
    marginHorizontal: 8,
    marginBottom: 8,
  },
  blockConfirmHandle: {
    width: 30,
    height: 4,
    borderRadius: 100,
    backgroundColor: colors.neutral[300],
    marginBottom: 24,
  },
  blockConfirmIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  blockConfirmTitle: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.black,
    marginBottom: 8,
    textAlign: 'center',
  },
  blockConfirmDescription: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.neutral[500],
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
    lineHeight: 24,
  },
  blockConfirmButtonBlock: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
    marginBottom: 8,
  },
  blockConfirmButtonGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blockConfirmButtonLabelBlock: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
  },
  blockConfirmButtonCancel: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    backgroundColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blockConfirmButtonLabelCancel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  // Ask Aira confirmation popup (Figma 2636-12667)
  askAiraConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  askAiraConfirmSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 16,
    paddingBottom: 32,
    paddingHorizontal: H_PADDING,
    alignItems: 'center',
    marginHorizontal: 8,
    marginBottom: 8,
  },
  askAiraConfirmHandle: {
    width: 30,
    height: 4,
    borderRadius: 100,
    backgroundColor: colors.neutral[300],
    marginBottom: 24,
  },
  askAiraConfirmContent: {
    alignItems: 'center',
    marginBottom: 24,
    gap: 8,
  },
  askAiraConfirmIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    // backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  askAiraConfirmDescription: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[500],
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  askAiraConfirmGenerateButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
    marginBottom: 16,
  },
  askAiraConfirmGenerateGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  askAiraConfirmGenerateLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
  },
  askAiraConfirmCheckRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  askAiraConfirmCheck: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  askAiraConfirmCheckSelected: {
    backgroundColor: colors.primary.purple,
    borderColor: colors.primary.purple,
  },
  askAiraConfirmCheckLabel: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  // Aira is thinking - API in progress (Figma 2636-13127, no cancel)
  airaThinkingBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  airaThinkingSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 16,
    marginHorizontal: 8,
    marginBottom: 8,
  },
  airaThinkingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    marginBottom: 16,
    height: 26,
  },
  airaThinkingHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  airaThinkingIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  airaThinkingTitle: {
    ...typography.bodyMedium,
    fontSize: 12,
    fontWeight: '400',
    color: colors.black,
  },
  airaThinkingHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.neutral[100],
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  airaThinkingLeftCount: {
    ...typography.bodyMedium,
    fontSize: 12,
    fontWeight: '500',
    color: colors.neutral[900],
  },
  airaThinkingSkeletons: {
    gap: 8,
    marginBottom: 16,
  },
  airaThinkingSkeletonRow: {
    borderWidth: 1,
    borderColor: colors.neutral[100],
    borderRadius: 16,
    padding: 12,
    gap: 4,
  },
  airaThinkingSkeleton: {
    height: 16,
    borderRadius: 10,
    backgroundColor: colors.neutral[50],
  },
  airaThinkingCancelButton: {
    alignSelf: 'center',
    minWidth: 116,
    height: 52,
    borderRadius: 100,
    paddingHorizontal: 32,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.02,
    shadowRadius: 14,
    elevation: 1,
  },
  airaThinkingCancelLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
    letterSpacing: 0.32,
  },
  // Suggestions from Aira (Figma 2636-13524)
  airaSuggestionsBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  airaSuggestionsSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    marginHorizontal: 8,
    marginBottom: 8,
    maxHeight: '90%',
    minHeight: 480,
  },
  airaSuggestionsHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.neutral[300],
    alignSelf: 'center',
    marginBottom: 20,
  },
  airaSuggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  airaSuggestionsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  airaSuggestionsTitle: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  airaSuggestionsListLabel: {
    ...typography.label,
    fontSize: 14,
    color: colors.neutral[600],
    marginBottom: 12,
  },
  airaSuggestionsList: {
    flex: 1,
    maxHeight: 380,
  },
  airaSuggestionsListContent: {
    gap: 12,
    paddingBottom: 16,
  },
  airaSuggestionCard: {
    borderWidth: 1,
    borderColor: colors.neutral[200],
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  airaSuggestionCardSelected: {
    backgroundColor: colors.primary[50],
    borderColor: colors.primary.purple,
  },
  airaSuggestionCardText: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '400',
    color: colors.neutral[900],
    lineHeight: 22,
  },
  airaSuggestionCardTextSelected: {
    color: colors.primary.purple,
    fontWeight: '500',
  },
  airaSuggestionsInsertButton: {
    width: '100%',
    height: 52,
    borderRadius: 100,
    overflow: 'hidden',
    marginTop: 16,
  },
  airaSuggestionsInsertGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  airaSuggestionsInsertLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
  },
  // Aira suggestion limit reached (Figma 2596-13414)
  airaLimitBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  airaLimitSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    minHeight: 332,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    marginHorizontal: 8,
    marginBottom: 8,
  },
  airaLimitHandle: {
    width: 30,
    height: 4,
    borderRadius: 100,
    backgroundColor: colors.neutral[300],
    alignSelf: 'center',
    marginBottom: 24,
  },
  airaLimitContent: {
    alignItems: 'center',
    marginBottom: 28,
    gap: 4,
    paddingHorizontal: 8,
  },
  airaLimitTitle: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.black,
    textAlign: 'center',
  },
  airaLimitDescription: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '400',
    color: colors.neutral[500],
    textAlign: 'center',
    lineHeight: 24,
  },
  airaLimitCountdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 24,
  },
  airaLimitCountdownPill: {
    backgroundColor: colors.primary[50],
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 40,
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  airaLimitCountdownText: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.primary.purple,
    letterSpacing: -0.24,
  },
  airaLimitCountdownColon: {
    ...typography.bodyMedium,
    fontSize: 24,
    fontWeight: '500',
    color: colors.primary.purple,
  },
  airaLimitOkayButton: {
    width: '100%',
    height: 54,
    borderRadius: 100,
    overflow: 'hidden',
  },
  airaLimitOkayGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  airaLimitOkayLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
  },
  scrollContent: {
    paddingHorizontal: H_PADDING,
    paddingBottom: 16,
  },
  datePill: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.primary[50],
    marginVertical: 16,
  },
  datePillText: {
    ...typography.bodyMedium,
    fontSize: 12,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  messagesLoadingWrap: {
    flex: 1,
    minHeight: 200,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  messagesLoadingText: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.neutral[600],
  },
  messagesLoadingMoreWrap: {
    alignSelf: 'center',
    paddingVertical: 8,
  },
  messageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 4,
  },
  messageRowReceived: {
    justifyContent: 'flex-start',
  },
  bubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderBottomRightRadius: 6,
  },
  bubbleSent: {
    backgroundColor: colors.primary.purple,
  },
  bubbleReceived: {
    backgroundColor: colors.primary[50],
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  bubbleReplyTo: {
    borderLeftWidth: 3,
    paddingLeft: 8,
    marginBottom: 6,
  },
  bubbleReplyToSent: {
    borderLeftColor: 'rgba(255,255,255,0.8)',
  },
  bubbleReplyToReceived: {
    borderLeftColor: colors.primary.purple,
  },
  bubbleReplyToLabel: {
    ...typography.bodyMedium,
    fontSize: 11,
    fontWeight: '600',
    color: colors.neutral[500],
    marginBottom: 2,
  },
  bubbleReplyToLabelSent: {
    color: 'rgba(255,255,255,0.9)',
  },
  bubbleReplyToPreview: {
    ...typography.bodyMedium,
    fontSize: 13,
    fontWeight: '500',
    color: colors.neutral[700],
  },
  bubbleReplyToPreviewSent: {
    color: 'rgba(255,255,255,0.95)',
  },
  bubbleText: {
    ...typography.bodyMedium,
    fontSize: 16,
    color: colors.black,
  },
  bubbleTextSent: {
    color: colors.white,
  },
  chatCallBubble: {
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    minWidth: 160,
    maxWidth: BUBBLE_MAX_WIDTH,
  },
  chatCallBubbleSent: {
    backgroundColor: colors.primary.purple,
  },
  chatCallBubbleReceived: {
    backgroundColor: colors.primary[50],
  },
  chatCallBubbleMissed: {
    backgroundColor: colors.neutral[50],
  },
  chatCallBubbleIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  chatCallBubbleTextWrap: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 2,
  },
  chatCallBubbleTitle: {
    ...typography.bodyMedium,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.28,
    flexShrink: 1,
  },
  chatCallBubbleTitleSent: {
    color: colors.white,
  },
  chatCallBubbleTitleReceived: {
    color: colors.black,
  },
  chatCallBubbleTitleMissed: {
    color: colors.semantic.error,
  },
  chatCallBubbleSubtitle: {
    ...typography.small,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.48,
    marginTop: 0,
    flexShrink: 1,
  },
  chatCallBubbleSubtitleSent: {
    color: colors.neutral[200],
  },
  chatCallBubbleSubtitleReceived: {
    color: colors.neutral[600],
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  timeRowReceived: {
    justifyContent: 'flex-start',
  },
  timeText: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.neutral[500],
  },
  voiceBubbleSent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary.purple,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minWidth: 180,
    maxWidth: BUBBLE_MAX_WIDTH,
    gap: 12,
  },
  voiceBubblePlay: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBubbleWaveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    height: 24,
  },
  voiceBubbleWaveformBar: {
    width: 2,
    borderRadius: 1,
    backgroundColor: colors.white,
    minHeight: 4,
  },
  voiceBubbleReceived: {
    backgroundColor: colors.primary[50],
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  voiceBubbleWaveformBarReceived: {
    backgroundColor: colors.primary.purple,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: MESSAGE_COMPOSER_ROW_PADDING_H,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: colors.white,
  },
  inputBarContent: {
    flex: 1,
    flexDirection: 'column',
  },
  typingIndicatorWrap: {
    paddingBottom: 6,
    paddingLeft: 4,
  },
  typingIndicatorText: {
    fontSize: 13,
    color: colors.neutral[500],
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: INPUT_PILL_BG,
    borderRadius: INPUT_RADIUS,
    paddingLeft: 16,
    paddingRight: 16,
    paddingVertical: 0,
    minHeight: INPUT_BAR_HEIGHT,
    maxHeight: INPUT_MAX_HEIGHT + 80,
    justifyContent: 'flex-start',
  },
  /** Vertically center composer row in pill when there are no attachment previews */
  inputWrapCentered: {
    justifyContent: 'center',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: MESSAGE_COMPOSER_ACTION_SIZE,
  },
  /** Multiline: pin + and field to bottom of growing pill */
  inputRowExpanded: {
    alignItems: 'flex-end',
  },
  /** Wraps TextInput + placeholder; centers short field with attach + send. */
  composerInputOuter: {
    flex: 1,
    minHeight: CHAT_INPUT_MIN_HEIGHT,
    justifyContent: 'flex-end',
    alignSelf: 'stretch',
    position: 'relative',
  },
  composerInputOuterSingleLine: {
    justifyContent: 'center',
  },
  composerPlaceholderWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
  },
  composerPlaceholderText: {
    ...typography.body,
    letterSpacing: 0.32,
    lineHeight: 22,
    color: colors.neutral[600],
  },
  attachmentsInsidePill: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
    overflow: 'visible',
  },
  /** Plus sits on pill surface — no nested ring (Figma 3339-7411 / Match composer) */
  attachButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginRight: 8,
  },
  input: {
    ...typography.body,
    minWidth: 100,
    color: colors.black,
    letterSpacing: 0.32,
    lineHeight: 22,
    paddingVertical: 13,
    paddingHorizontal: 0,
    margin: 0,
  },
  chatInput: {
    width: '100%',
    alignSelf: 'stretch',
    minHeight: CHAT_INPUT_MIN_HEIGHT,
    maxHeight: CHAT_INPUT_MAX_HEIGHT,
    paddingTop: Platform.OS === 'ios' ? 10 : 6,
    paddingBottom: Platform.OS === 'ios' ? 10 : 6,
    paddingHorizontal: 0,
    fontSize: 16,
    color: '#000',
    ...Platform.select({
      android: {
        includeFontPadding: false,
      },
    }),
    textAlignVertical: 'top',
  },
  chatInputSingleLine: {
    paddingTop: 0,
    paddingBottom: 0,
    minHeight: CHAT_INPUT_MIN_HEIGHT,
    maxHeight: CHAT_INPUT_MIN_HEIGHT,
  },
  askAiraChipGradientWrap: {
    alignSelf: 'center',
    borderRadius: 20,
    padding: 1,
    overflow: 'hidden',
  },
  askAiraChipInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 19,
    backgroundColor: colors.white,
  },
  askAiraChipText: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary.purple,
  },
  /** Figma 2447-5356: Ask Aira chip 32x32, rounded, elevation/01 shadow */
  askAiraButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 16,
      },
      android: { elevation: 2 },
    }),
  },
  insertButton: {
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  insertButtonText: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  insertButtonGradientWrap: {
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  insertButtonGradientText: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: colors.white,
  },
  generatedRepliesStrip: {
    maxHeight: 88,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: colors.white,
  },
  generatedRepliesStripContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  generatedReplyChipTouchable: {
    maxWidth: SCREEN_WIDTH * 0.7,
  },
  generatedReplyChipGradientWrap: {
    borderRadius: 20,
    padding: 1,
    overflow: 'hidden',
  },
  generatedReplyChipInner: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 19,
    backgroundColor: colors.white,
    maxWidth: SCREEN_WIDTH * 0.7 - 2,
  },
  generatedReplyChipTextSelected: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[800],
  },
  generatedReplyChipUnselected: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: colors.neutral[100],
    maxWidth: SCREEN_WIDTH * 0.7,
  },
  generatedReplyChipTextUnselected: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  sendButton: {
    width: SEND_BUTTON_SIZE,
    height: SEND_BUTTON_SIZE,
    borderRadius: SEND_BUTTON_SIZE / 2,
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    alignSelf: 'center',
  },
  /** Mic / idle — same treatment as MatchScreen sendButtonDisabled */
  sendButtonMic: {
    backgroundColor: INPUT_PILL_BG,
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  inputArea: {
    backgroundColor: colors.white,
  },
  bottomComposerContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    zIndex: 10,
  },
  replyToBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
marginHorizontal: 16,
borderRadius: 16,
    // paddingHorizontal: 16,
    paddingLeft: 0,
    paddingRight: 12,
    backgroundColor:'#f3f3f3',
    // borderTopWidth: StyleSheet.hairlineWidth,
    // borderTopColor: colors.neutral[200],
  },
  replyToBarGradientBorder: {
    width: 4,
    borderTopLeftRadius: 32,
    borderBottomLeftRadius: 32,
    marginRight: 12,
    alignSelf: 'stretch',
  },
  replyToBarContent: {
    flex: 1,
    minWidth: 0,
  },
  replyToBarLabel: {
    ...typography.bodyMedium,
    fontSize: 12,
    fontWeight: '500',
    color: colors.neutral[500],
    marginBottom: 2,
  },
  replyToBarPreview: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[800],
  },
  replyToBarDismiss: {
    width: 32,
    height: 32,
    borderRadius: 16,
    // backgroundColor: colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  generatingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: GENERATING_BAR_HEIGHT,
    paddingTop: 8,
    paddingBottom: 8,
    gap: GENERATING_BAR_GAP,
    backgroundColor: colors.white,
  },
  generatingBubbleGradientWrap: {
    alignSelf: 'flex-start',
    borderRadius: GENERATING_PILL_BORDER_RADIUS,
    padding: 1,
    overflow: 'hidden',
  },
  generatingBubbleInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: GENERATING_PILL_GAP,
    paddingVertical: GENERATING_PILL_PADDING_V,
    paddingHorizontal: GENERATING_PILL_PADDING_H,
    borderRadius: GENERATING_PILL_BORDER_RADIUS - 1,
    backgroundColor: colors.white,
  },
  generatingBubbleText: {
    ...typography.bodyMedium,
    fontSize: 15,
    fontWeight: '500',
    color: colors.primary.purple,
  },
  // Mask for gradient text: mask must be opaque (black) so gradient shows through text shape
  generatingBubbleTextMask: {
    backgroundColor: 'transparent',
    color: colors.black,
  },
  generatingGradientTextWrap: {
    position: 'relative',
    alignSelf: 'flex-start',
  },
  generatingGradientTextPlaceholder: {
    opacity: 0,
  },
  generatingGradientTextOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  generatingCancel: {
    width: GENERATING_CANCEL_SIZE,
    height: GENERATING_CANCEL_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'transparent',
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  voiceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    backgroundColor: colors.white,
    gap: 8,
  },
  voiceBarTrash: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.semantic.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBarPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: INPUT_PILL_BG,
    borderRadius: INPUT_RADIUS,
    paddingLeft: 12,
    paddingRight: 12,
    paddingVertical: 10,
    minHeight: INPUT_BAR_HEIGHT,
    gap: 12,
  },
  voiceBarPlayPause: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBarWaveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    height: 24,
  },
  voiceBarWaveformBar: {
    width: 2,
    borderRadius: 1,
    backgroundColor: colors.neutral[600],
    minHeight: 4,
  },
  voiceBarTimer: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
    minWidth: 36,
  },
  voiceBarSend: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  attachmentPreviewWrapper: {
    position: 'relative',
    overflow: 'visible',
  },
  attachmentPreview: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: colors.neutral[100],
    overflow: 'hidden',
  },
  attachmentPreviewImage: {
    width: '100%',
    height: '100%',
  },
  attachmentPreviewFileCard: {
    width: 72,
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    paddingTop: 8,
    paddingHorizontal: 8,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  attachmentPreviewFileType: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.neutral[600],
    marginBottom: 4,
  },
  attachmentPreviewFileName: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.black,
  },
  attachmentPreviewFile: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachmentRemove: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.neutral[700],
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  imageBubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    overflow: 'hidden',
  },
  imageBubbleReceived: {
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  imageBubbleImage: {
    width: '100%',
    height: '100%',
  },
  fileBubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary.purple,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
  },
  fileBubbleReceived: {
    backgroundColor: colors.primary[50],
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  fileBubbleIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileBubbleName: {
    flex: 1,
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.white,
  },
  fileBubbleNameReceived: {
    color: colors.black,
  },
  // Request mode: Decline / Accept / Block & Report (Figma 2259-18847)
  requestActionBar: {
    paddingHorizontal: H_PADDING,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: colors.white,
    gap: 8,
  },
  requestActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  requestDeclineButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    backgroundColor: colors.neutral[50],
    justifyContent: 'center',
    alignItems: 'center',
  },
  requestAcceptButton: {
    flex: 1,
    height: 54,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  requestDeclineLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  requestAcceptLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.white,
  },
  requestBlockReportWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  requestBlockReportText: {
    ...typography.label,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.28,
    color: colors.neutral[700],
  },
});
