import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, typography } from '../../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const H_PADDING = 16;
const INPUT_PILL_BG = '#f3f3f3';
const INPUT_RADIUS = 24;
export const INPUT_BAR_HEIGHT = 56;
const INPUT_MAX_HEIGHT = 120;
const ATTACH_BUTTON_SIZE = 40;
const IMAGE_BUBBLE_SIZE = 200;
const SEND_BUTTON_SIZE = 40;
export const BUBBLE_MAX_WIDTH = SCREEN_WIDTH * 0.75;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.white,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.neutral[200],
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.neutral[200],
    marginRight: 12,
  },
  headerName: {
    flex: 1,
    ...typography.bodyMedium,
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
  },
  moreButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 4,
  },
  moreMenuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  moreMenu: {
    position: 'absolute',
    right: H_PADDING,
    minWidth: 160,
    backgroundColor: '#F2F2F2',
    borderRadius: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
    paddingVertical: 8,
  },
  moreMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 8,
  },
  moreMenuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    // backgroundColor: colors.neutral[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  moreMenuIconWrapReport: {
    backgroundColor: 'rgba(230, 0, 0, 0.12)',
  },
  moreMenuLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  moreMenuLabelReport: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.semantic.error,
  },
  messageContextBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageContextBubble: {
    backgroundColor: colors.white,
    borderRadius: 16,
    minWidth: 160,
    paddingVertical: 8,
    paddingHorizontal: 4,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
  },
  messageContextItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 12,
  },
  messageContextItemDelete: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 12,
  },
  messageContextLabel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.black,
  },
  messageContextLabelDelete: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '500',
    color: colors.semantic.error,
  },
  deleteConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  deleteConfirmSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 12,
    paddingBottom: 34,
    paddingHorizontal: H_PADDING,
    alignItems: 'center',
  },
  deleteConfirmHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.neutral[300],
    marginBottom: 20,
  },
  deleteConfirmTitle: {
    ...typography.bodyMedium,
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
    marginBottom: 8,
    textAlign: 'center',
  },
  deleteConfirmDescription: {
    ...typography.bodyMedium,
    fontSize: 15,
    fontWeight: '400',
    color: colors.neutral[600],
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  deleteConfirmButtonDelete: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.semantic.error,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  deleteConfirmButtonCancel: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.neutral[100],
    borderWidth: 1,
    borderColor: colors.neutral[200],
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmButtonLabelDelete: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '600',
    color: colors.white,
  },
  deleteConfirmButtonLabelCancel: {
    ...typography.bodyMedium,
    fontSize: 16,
    fontWeight: '600',
    color: colors.black,
  },
  scrollContent: {
    paddingHorizontal: H_PADDING,
    paddingBottom: 16,
  },
  datePill: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.primary[50],
    marginVertical: 16,
  },
  datePillText: {
    ...typography.bodyMedium,
    fontSize: 12,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  messageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 4,
  },
  messageRowReceived: {
    justifyContent: 'flex-start',
  },
  bubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    borderBottomRightRadius: 6,
  },
  bubbleSent: {
    backgroundColor: colors.primary.purple,
  },
  bubbleReceived: {
    backgroundColor: colors.primary[50],
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  bubbleText: {
    ...typography.bodyMedium,
    fontSize: 16,
    color: colors.black,
  },
  bubbleTextSent: {
    color: colors.white,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  timeRowReceived: {
    justifyContent: 'flex-start',
  },
  timeText: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.neutral[500],
  },
  voiceBubbleSent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary.purple,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minWidth: 180,
    maxWidth: BUBBLE_MAX_WIDTH,
    gap: 12,
  },
  voiceBubblePlay: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBubbleWaveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    height: 24,
  },
  voiceBubbleWaveformBar: {
    width: 2,
    borderRadius: 1,
    backgroundColor: colors.white,
    minHeight: 4,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: colors.white,
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: INPUT_PILL_BG,
    borderRadius: INPUT_RADIUS,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    minHeight: INPUT_BAR_HEIGHT,
    maxHeight: INPUT_MAX_HEIGHT + 80,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    minHeight: 40,
  },
  attachmentsInsidePill: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
    overflow: 'visible',
  },
  attachButton: {
    width: ATTACH_BUTTON_SIZE,
    height: ATTACH_BUTTON_SIZE,
    borderRadius: ATTACH_BUTTON_SIZE / 2,
    backgroundColor: INPUT_PILL_BG,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 16,
      },
      android: { elevation: 2 },
    }),
  },
  input: {
    flex: 1,
    minWidth: 100,
    minHeight: 24,
    maxHeight: INPUT_MAX_HEIGHT - 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 16,
    fontWeight: '400',
    color: colors.black,
    margin: 0,
  },
  askAiraChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: colors.white,
    borderColor: colors.primary.purple,
    // marginRight: 4,
    // marginLeft: 4,
  },
  askAiraChipText: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary.purple,
  },
  sendButton: {
    width: SEND_BUTTON_SIZE,
    height: SEND_BUTTON_SIZE,
    borderRadius: SEND_BUTTON_SIZE / 2,
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    marginBottom: 8,
  },
  sendButtonMic: {
    backgroundColor: INPUT_PILL_BG,
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  inputArea: {
    backgroundColor: colors.white,
  },
  generatingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    gap: 8,
    backgroundColor: colors.white,
  },
  generatingBubble: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    backgroundColor: colors.white,
  },
  generatingBubbleText: {
    ...typography.bodyMedium,
    fontSize: 15,
    fontWeight: '500',
    color: colors.primary.purple,
  },
  // Mask for gradient text: opaque so gradient (#CB7BF5 → #7742F0) shows through
  generatingBubbleTextMask: {
    backgroundColor: 'transparent',
    color: colors.black,
  },
  generatingCancel: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    backgroundColor: colors.white,
    gap: 8,
  },
  voiceBarTrash: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.semantic.error,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBarPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: INPUT_PILL_BG,
    borderRadius: INPUT_RADIUS,
    paddingLeft: 12,
    paddingRight: 12,
    paddingVertical: 10,
    minHeight: INPUT_BAR_HEIGHT,
    gap: 12,
  },
  voiceBarPlayPause: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceBarWaveform: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    height: 24,
  },
  voiceBarWaveformBar: {
    width: 2,
    borderRadius: 1,
    backgroundColor: colors.neutral[600],
    minHeight: 4,
  },
  voiceBarTimer: {
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
    minWidth: 36,
  },
  voiceBarSend: {
    width: SEND_BUTTON_SIZE,
    height: SEND_BUTTON_SIZE,
    borderRadius: SEND_BUTTON_SIZE / 2,
    backgroundColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  attachmentPreviewWrapper: {
    position: 'relative',
    overflow: 'visible',
  },
  attachmentPreview: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: colors.neutral[100],
    overflow: 'hidden',
  },
  attachmentPreviewImage: {
    width: '100%',
    height: '100%',
  },
  attachmentPreviewFileCard: {
    width: 72,
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    paddingTop: 8,
    paddingHorizontal: 8,
    paddingBottom: 8,
    overflow: 'hidden',
  },
  attachmentPreviewFileType: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.neutral[600],
    marginBottom: 4,
  },
  attachmentPreviewFileName: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.black,
  },
  attachmentPreviewFile: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachmentRemove: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.neutral[700],
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  imageBubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    overflow: 'hidden',
  },
  imageBubbleReceived: {
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  imageBubbleImage: {
    width: IMAGE_BUBBLE_SIZE,
    height: IMAGE_BUBBLE_SIZE,
  },
  fileBubble: {
    maxWidth: BUBBLE_MAX_WIDTH,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary.purple,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 12,
  },
  fileBubbleReceived: {
    backgroundColor: colors.primary[50],
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 6,
  },
  fileBubbleIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileBubbleName: {
    flex: 1,
    ...typography.bodyMedium,
    fontSize: 14,
    fontWeight: '500',
    color: colors.white,
  },
  fileBubbleNameReceived: {
    color: colors.black,
  },
});
