import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, typography } from '../../../theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const CIRCLE_SIZE = Math.min(SCREEN_WIDTH * 0.8, 300);
const CIRCLE_RADIUS = CIRCLE_SIZE / 2;

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: colors.black,
  },
  safeArea: {
    flex: 1,
  },
  backgroundGlow: {
    position: 'absolute',
    width: '100%',
    height: 600,
    alignSelf: 'center',
    top: '15%',
    opacity: 0.3,
  },
  headerContainer: {
  // Align back arrow with other profile screens
  paddingTop: 16,
  paddingHorizontal: 20,
    zIndex: 10,
  },
  content: {
    flex: 1,
    // paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 36,
    marginBottom: spacing.sm,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    fontFamily: typography.fontFamily.regular,
    color: colors.white,
    lineHeight: 22,
    textAlign: 'center',
    opacity: 0.8,
    marginBottom: spacing.xl * 2,
  },
  cameraContainer: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraFrame: {
    width: SCREEN_WIDTH,
    height: SCREEN_WIDTH,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  camera: {
    width: SCREEN_WIDTH,
    height: SCREEN_WIDTH,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  circleFrame: {
    width: CIRCLE_SIZE,
    height: CIRCLE_SIZE,
    borderRadius: CIRCLE_RADIUS,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  circleBorder: {
    width: CIRCLE_SIZE,
    height: CIRCLE_SIZE,
    borderRadius: CIRCLE_RADIUS,
    borderWidth: 3,
    borderColor: colors.white,
    borderStyle: 'dashed',
  },
  defaultCameraIconOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  // Overlay masks outside the circle
  overlayTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 1,
  },
  overlayBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 1,
  },
  overlayLeft: {
    position: 'absolute',
    top: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    left: 0,
    width: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    height: CIRCLE_SIZE,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 1,
  },
  overlayRight: {
    position: 'absolute',
    top: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    right: 0,
    width: (SCREEN_WIDTH - CIRCLE_SIZE) / 2,
    height: CIRCLE_SIZE,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    zIndex: 1,
  },
  buttonContainer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl * 1.5,
  },
  button: {
    width: '100%',
    height: 54,
    borderRadius: 100,
  },
  // Verifying screen
  verifyingContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
  },
  verifyingSelfieCircle: {
    width: CIRCLE_SIZE,
    height: CIRCLE_SIZE,
    borderRadius: CIRCLE_RADIUS,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: colors.white,
    marginBottom: spacing.xl * 2,
  },
  verifyingSelfieImage: {
    width: '100%',
    height: '100%',
  },
  verifyingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl * 1.5,
    borderRadius: 100,
    gap: spacing.sm,
  },
  verifyingPillText: {
    fontSize: 16,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
  },
  spinner: {
    marginBottom: spacing.xl,
  },
  verifyingTitle: {
    fontSize: 24,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 32,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  verifyingSubtitle: {
    fontSize: 16,
    fontFamily: typography.fontFamily.regular,
    color: colors.white,
    lineHeight: 22,
    textAlign: 'center',
    opacity: 0.85,
  },
  // Verified success screen (Figma 886-3849)
  verifiedBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
  },
  verifiedBackgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  verifiedContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
  },
  verifiedGreenCircle: {
    width: CIRCLE_SIZE,
    height: CIRCLE_SIZE,
    borderRadius: CIRCLE_RADIUS,
    borderWidth: 4,
    borderColor: colors.semantic.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifiedCheckmarkWrapper: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifiedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.semantic.success,
    paddingVertical: 16,
    paddingHorizontal: spacing.xl * 2,
    borderRadius: 100,
    gap: spacing.sm,
  },
  verifiedButtonText: {
    fontSize: 18,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
  },
  verifiedIconWrapper: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  verifiedTitle: {
    fontSize: 28,
    fontFamily: typography.fontFamily.medium,
    color: colors.white,
    lineHeight: 36,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  verifiedSubtitle: {
    fontSize: 16,
    fontFamily: typography.fontFamily.regular,
    color: colors.white,
    lineHeight: 22,
    textAlign: 'center',
    opacity: 0.85,
  },
});

